version: "3.5"

services:
  frontend_server:
    image: frontend-test
    build: ./example-frontend
    ports:
      - 5000:5000
    container_name: frontend

  backend_server:
    image: backend-test
    build: ./example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis_server
      - POSTGRES_HOST=postgres_server
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres

    container_name: backend
    depends_on:
      - postgres_server
      - redis_server

  redis_server:
    image: redis
    restart: unless-stopped
    container_name: redis

  postgres_server:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: postgres

